"""Bonus mini-product UI — Lab 17 memory agent demo (STUDENT starter).

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by Gemini grounded in the
   retrieved memory context (gemini-2.5-flash-lite by default).

The page shell, budget metrics, and Gemini chat are wired for you. Your job is
the ONE function marked `BONUS TODO`: `retrieve_for_case(...)`.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import sys
import uuid
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import gemini_available, generate_reply
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, join_nonempty, load_dataset, load_json
from src.zep_common import get_zep_client
from src.zep_memory import ZepMemory

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

CSS = """
<style>
.block-container { padding-top: 2rem; max-width: 1200px; }
.lab-badge {
    display:inline-block; padding:2px 10px; border-radius:999px;
    color:#fff; font-size:0.75rem; font-weight:600; letter-spacing:.02em;
    margin-right:6px;
}
.lab-card {
    border:1px solid rgba(128,128,128,.25); border-radius:12px;
    padding:14px 16px; margin-bottom:12px; background:rgba(127,127,127,.06);
}
.lab-kv { font-size:0.85rem; opacity:.85; }
.lab-kv b { opacity:1; }
.stChatMessage { border-radius:12px; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def seed_messages_for(case: dict[str, Any]) -> list[dict[str, str]]:
    """Messages that make up the case's short-term window.

    Fixture cases (E10) carry their own transcript; the rest replay the
    matching thread from data/sessions.json (E01 -> thread minh-s1).
    """
    if case.get("fixture_messages"):
        return list(case["fixture_messages"])
    for user in load_dataset()["users"]:
        if user["user_id"] != case.get("user_id"):
            continue
        for session in user.get("sessions", []):
            if session["thread_id"] == case.get("thread_id"):
                return list(session["messages"])
    return []


def wanted_layers(case: dict[str, Any], all_layers: bool) -> set[str]:
    """Which durable layers to fetch for this case.

    Default mirrors the benchmark: one layer per case, or `retrieve_layers`
    for a mixed case. The chat box passes all_layers=True — a live turn has no
    declared expected layer, so it draws on everything.
    """
    if all_layers:
        return {"short_term", "long_term", "episodic", "semantic"}
    layer = case.get("expected_layer", "mixed")
    if layer == "mixed":
        return set(case.get("retrieve_layers") or ["short_term", "long_term", "semantic"])
    return {layer}


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
    *,
    all_layers: bool = False,
    zep: ZepMemory | None = None,
    live_thread_id: str | None = None,
) -> dict[str, Any]:
    """Run layered retrieval for the loaded case and merge under the budget.

    When `live_thread_id` is given (the chat box), the long-term layer reads
    the context block of that live thread instead of priming the case's eval
    thread — priming recreates a thread, which would discard the chat history
    just persisted to Zep.
    """
    query = case.get("query", "")
    user_id = case.get("user_id", "")
    wanted = wanted_layers(case, all_layers)
    layers = {"short_term": "", "long_term": "", "episodic": "", "semantic": ""}

    if "short_term" in wanted:
        stm = ShortTermMemory(strategy="sliding", max_recent_messages=6, pressure_tokens=450)
        for msg in seed_messages_for(case) + list(extra_messages):
            stm.add(msg["role"], msg["content"])
        layers["short_term"] = stm.render()

    if "long_term" in wanted:
        if live_thread_id and zep is not None:
            layers["long_term"] = join_nonempty(
                [
                    zep.get_context_block(live_thread_id),
                    zep.search_user_graph(user_id, query, scope="edges", limit=memory.fact_limit),
                ],
                sep="\n\n",
            )
        else:
            layers["long_term"] = memory.retrieve_long_term(
                user_id=user_id,
                thread_id=case.get("thread_id", ""),
                query=query,
            )

    if "episodic" in wanted:
        layers["episodic"] = memory.retrieve_episodic(user_id, query)

    if "semantic" in wanted:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged, budget = memory.assemble_context(layers)
    return {"merged_context": merged, "layers": layers, "budget": budget}


def main() -> None:
    st.set_page_config(page_title="Lab 17 Memory Demo", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 — Memory Agent Demo")
    st.caption("Load a test case, inspect layered retrieval, then keep chatting as that user.")

    with st.sidebar:
        st.header("⚙️ Setup")
        zep_ok = bool(settings.zep_api_key)
        st.markdown(("✅" if zep_ok else "⚠️") + " Zep API key "
                    + ("configured" if zep_ok else "missing"))
        st.markdown(("✅" if gemini_available() else "⚠️") + " Gemini key "
                    + ("configured" if gemini_available() else "missing"))
        st.caption(f"Chat model: `{settings.gemini_model}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Test case", labels)
        case = cases[labels.index(chosen)]

    st.markdown(
        f'<div class="lab-card">{layer_badge(case.get("expected_layer","?"))}'
        f'<b>{case["id"]}</b><br>'
        f'<span class="lab-kv"><b>User:</b> {case.get("user_id","-")} &nbsp;·&nbsp; '
        f'<b>Thread:</b> {case.get("thread_id","-")}</span>'
        f'<p style="margin:.5rem 0 0">{case.get("query","")}</p>'
        f'<span class="lab-kv">{case.get("description","")}</span></div>',
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)
        st.session_state.pop("live_thread_id", None)

    col_run, _ = st.columns([1, 3])
    if col_run.button("▶️ Run retrieval on this case", use_container_width=True):
        try:
            memory = StudentMemory(get_zep_client())
            st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)

    result = st.session_state.get("last_result")
    if result:
        st.markdown("### 🔎 Retrieved context")
        active = [k for k, v in result["layers"].items() if v.strip()]
        st.markdown(" ".join(layer_badge(k) for k in active) or "_(nothing retrieved)_",
                    unsafe_allow_html=True)

        if result.get("budget"):
            cols = st.columns(4)
            for i, layer in enumerate(("short_term", "long_term", "episodic", "semantic")):
                b = result["budget"].get(layer, {})
                cols[i].metric(
                    layer,
                    f"{b.get('used_tokens', 0)} tok",
                    help=f"limit {b.get('limit_tokens', 0)} · raw {b.get('raw_tokens', 0)}",
                )

        with st.expander("Merged context (budget-trimmed)", expanded=True):
            st.code(result.get("merged_context") or "(empty)", language="markdown")
        for name, text in result["layers"].items():
            if text.strip():
                with st.expander(f"{name} evidence"):
                    st.write(text)

    st.markdown("### 💬 Continue chat as this user")
    for msg in st.session_state.get("chat", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    prompt = st.chat_input("Message as this user…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            client = get_zep_client()
            memory = StudentMemory(client)
            zep = ZepMemory(client)

            # One live Zep thread per chat, kept apart from the case's eval
            # thread so retrieval never deletes the conversation.
            thread_id = st.session_state.get("live_thread_id")
            if not thread_id:
                zep.on_signup(case["user_id"])
                thread_id = zep.start_thread(
                    case["user_id"], f"ui-{case['id']}-{uuid.uuid4().hex[:8]}".lower()
                )
                st.session_state.live_thread_id = thread_id

            # 1. persist the incoming user message
            zep.record_message(thread_id, "user", prompt)

            # 2. retrieve — Zep context block for this thread + the other layers
            follow = retrieve_for_case(
                memory,
                {**case, "query": prompt},
                st.session_state.chat,
                all_layers=True,
                zep=zep,
                live_thread_id=thread_id,
            )
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")

            # 3. answer with that context in the system prompt
            if gemini_available():
                reply = generate_reply(context, st.session_state.chat[:-1], prompt)
            else:
                reply = ("_(Gemini key missing — showing retrieved context instead)_\n\n"
                         + (context[:1500] or "(no memory retrieved)"))

            # 4. persist the assistant message
            zep.record_message(thread_id, "assistant", reply)

            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)


if __name__ == "__main__":
    main()
